function [fermentationDataset1,respirationDataset1,respirationDataset2,modelProteomics ]=importProteomics()

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/linoste/Documents/GitHub/Crabtree/proteomics/fermentationDataset1.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 14-May-2020 13:36:09

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A1:E5005";

% Specify column names and types
opts.VariableNames = ["ProteinId", "GeneSymbol", "Var3", "Var4", "glucose"];
opts.SelectedVariableNames = ["ProteinId", "GeneSymbol", "glucose"];
opts.VariableTypes = ["string", "string", "char", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["ProteinId", "GeneSymbol", "Var3", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ProteinId", "GeneSymbol", "Var3", "Var4"], "EmptyFieldRule", "auto");

% Import the data
fermentationDataset1 = readtable("/Users/linoste/Documents/GitHub/Crabtree/proteomics/fermentationDataset1.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/linoste/Documents/GitHub/Crabtree/proteomics/respirationDataset2.xlsx
%    Worksheet: SI_Table3
%
% Auto-generated by MATLAB on 15-May-2020 16:58:22

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "SI_Table3";
opts.DataRange = "A1:B2145";

% Specify column names and types
opts.VariableNames = ["GeneID", "REF"];
opts.VariableTypes = ["string", "double"];

% Specify variable properties
opts = setvaropts(opts, "GeneID", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "GeneID", "EmptyFieldRule", "auto");

% Import the data
respirationDataset1 = readtable("/Users/linoste/Documents/GitHub/Crabtree/proteomics/respirationDataset2.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/linoste/Documents/GitHub/Crabtree/proteomics/respirationDataset1.xlsx
%    Worksheet: ProteinQuant
%
% Auto-generated by MATLAB on 02-Jun-2020 21:44:51

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 18);

% Specify sheet and range
opts.Sheet = "ProteinQuant";
opts.DataRange = "A1:R1904";

% Specify column names and types
opts.VariableNames = ["Var1", "Protein", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "FinalQuant"];
opts.SelectedVariableNames = ["Protein", "FinalQuant"];
opts.VariableTypes = ["char", "string", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Protein", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Protein", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17"], "EmptyFieldRule", "auto");

% Import the data
respirationDataset2 = readtable("/Users/linoste/Documents/GitHub/Crabtree/proteomics/respirationDataset1.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts