function [rellativeAbundance,fermentationDataset1,respirationDataset1]=proteomicsData()
 %% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/linoste/Documents/GitHub/Crabtree/proteomics/rellativeAbundance.txt
%
% Auto-generated by MATLAB on 15-May-2020 22:48:04

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [13, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["internal_id", "string_external_id", "abundance"];
opts.VariableTypes = ["double", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "string_external_id", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "string_external_id", "EmptyFieldRule", "auto");

% Import the data
rellativeAbundance = readtable("/Users/linoste/Documents/GitHub/Crabtree/proteomics/rellativeAbundance.txt", opts);

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/linoste/Documents/GitHub/Crabtree/proteomics/fermentationDataset1.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 14-May-2020 13:36:09

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A1:E5005";

% Specify column names and types
opts.VariableNames = ["ProteinId", "GeneSymbol", "Var3", "Var4", "glucose"];
opts.SelectedVariableNames = ["ProteinId", "GeneSymbol", "glucose"];
opts.VariableTypes = ["string", "string", "char", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["ProteinId", "GeneSymbol", "Var3", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ProteinId", "GeneSymbol", "Var3", "Var4"], "EmptyFieldRule", "auto");

% Import the data
fermentationDataset1 = readtable("/Users/linoste/Documents/GitHub/Crabtree/proteomics/fermentationDataset1.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/linoste/Documents/GitHub/Crabtree/proteomics/respirationDataset2.xlsx
%    Worksheet: SI_Table3
%
% Auto-generated by MATLAB on 15-May-2020 16:58:22

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "SI_Table3";
opts.DataRange = "A1:B2145";

% Specify column names and types
opts.VariableNames = ["GeneID", "REF"];
opts.VariableTypes = ["string", "double"];

% Specify variable properties
opts = setvaropts(opts, "GeneID", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "GeneID", "EmptyFieldRule", "auto");

% Import the data
respirationDataset1 = readtable("/Users/linoste/Documents/GitHub/Crabtree/proteomics/respirationDataset2.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
