function [rellativeAbundance, rapamycin , geneExprG0, geneExprG1]=loadData()
% loading regulation applied by Boolean
load('/Users/linoste/Documents/GitHub/Crabtree/Code/Multiscale_Linnea/data/GeneExprG0.mat');
geneExprG0 = GeneExpr;

load('/Users/linoste/Documents/GitHub/Crabtree/Code/Multiscale_Linnea/data/GeneExprG1.mat');
geneExprG1 = GeneExpr;

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/linoste/Documents/GitHub/Crabtree/proteomics/rapamycin.xls
%    Worksheet: A. I(g) Intensity
%
% Auto-generated by MATLAB on 18-Jun-2020 12:00:46

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 17);

% Specify sheet and range
opts.Sheet = "A. I(g) Intensity";
opts.DataRange = "A1:Q4149";

% Specify column names and types
opts.VariableNames = ["ORF", "Genename", "WT1", "WT2", "WT3", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "RAP700"];
opts.SelectedVariableNames = ["ORF", "Genename", "WT1", "WT2", "WT3", "RAP700"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["ORF", "Genename", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ORF", "Genename", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16"], "EmptyFieldRule", "auto");

% Import the data
rapamycin = readtable("/Users/linoste/Documents/GitHub/Crabtree/proteomics/rapamycin.xls", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/linoste/Documents/GitHub/Crabtree/proteomics/rellativeAbundance.txt
%
% Auto-generated by MATLAB on 15-May-2020 22:48:04

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [13, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["internal_id", "string_external_id", "abundance"];
opts.VariableTypes = ["double", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "string_external_id", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "string_external_id", "EmptyFieldRule", "auto");

% Import the data
rellativeAbundance = readtable("/Users/linoste/Documents/GitHub/Crabtree/proteomics/rellativeAbundance.txt", opts);


%% Clear temporary variables
clear opts
