function [rellativeAbundance,proteomics, D,Dregulated, enzUsages_reducedYeast,enzUsages_reducedYeastRegulated, geneExprG0, geneExprG1]=loadData()

%% Load data from publication
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = "all proteins relative abundance";
opts.DataRange = "A2:M3610";

% Specify column names and types
opts.VariableNames = ["ProteinAccession", "GeneSymbol", "Peptides", "h5", "h7", "h9", "h11", "h13", "h15", "h17", "h25", "h29", "h33"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["ProteinAccession", "GeneSymbol"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ProteinAccession", "GeneSymbol"], "EmptyFieldRule", "auto");

% Import the data
proteomics = readtable("/Users/linoste/Documents/GitHub/Crabtree/Comprehensive Temporal Protein Dynamics during the Diauxic Shift in Saccharomyces cerevisiae/supp_M114.045849_mcp.M114.045849-2.xlsx", opts, "UseExcel", false);
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/linoste/Documents/GitHub/Crabtree/proteomics/rellativeAbundance.txt
%
% Auto-generated by MATLAB on 15-May-2020 22:48:04

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [13, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["internal_id", "string_external_id", "abundance"];
opts.VariableTypes = ["double", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "string_external_id", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "string_external_id", "EmptyFieldRule", "auto");

% Import the data
rellativeAbundance = readtable("/Users/linoste/Documents/GitHub/Crabtree/proteomics/rellativeAbundance.txt", opts);


%% Clear temporary variables
clear opts

%% Load data from simulation 
% Loading enzyme usages unconstrained
path2Sim='/Users/linoste/Documents/GitHub/Crabtree/Code/Multiscale_Linnea/results/multiscale20200506nr2/';
path2Sim2='/Users/linoste/Documents/GitHub/Crabtree/Code/Multiscale_Linnea/results/multiscale20200525nr7/';
'/Users/linoste/Documents/GitHub/Crabtree/Code/Multiscale_Linnea/results/checkTF20200529'
filename='enzUsage_VarAnalysis_D_';
format='.txt';
D=cell(1,81);
i = 1;
for dilutionrate=0:(0.4/80):0.4
    D{i}=readtable([path2Sim filename strrep(num2str(dilutionrate),'0.','') format]);
    i=1+i;
end

Dregulated=cell(1,81);
i = 1;
for dilutionrate=0:(0.4/80):0.4
    Dregulated{i}=readtable([path2Sim2 filename strrep(num2str(dilutionrate),'0.','') format]);
    i=1+i;
end
% Loading enzyme usages in percentages for each dilution rate
enzUsages_reducedYeast=readtable([path2Sim 'enzUsages_reducedYeast.txt']);
enzUsages_reducedYeastRegulated=readtable([path2Sim2 'enzUsages_reducedYeast.txt']);
% loading regulation applied by Boolean
load('/Users/linoste/Documents/GitHub/Crabtree/Code/Multiscale_Linnea/data/GeneExprG0.mat');
geneExprG0 = GeneExpr;

load('/Users/linoste/Documents/GitHub/Crabtree/Code/Multiscale_Linnea/data/GeneExprG1.mat');
geneExprG1 = GeneExpr;
